1. Создайте трехмерный массив (каждый массив должен содержать две строки и четыре столбца) и определите его количество измерений.

In [1]:
import numpy as np

shape = (3, 2, 4)
arr = np.zeros(shape)

dimensions =  arr.ndim 

print(arr)
print("Количество измерений:", dimensions)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
Количество измерений: 3


2. Создайте матрицу 3x4 заполненную единицами и определите её размеры.

In [2]:
import numpy as np

matrix = np.ones((3, 4)) 

matrix_shape =  matrix.shape

print("Матрица:")
print(matrix)
print("Размеры матрицы:", matrix_shape)

Матрица:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Размеры матрицы: (3, 4)


3.  Повторите созданный массив с элементами(1, 2, 3) 4 раза вдоль оси 0(строки) и дополнительно, каждую строку массива увеличьте по размеру в два раза с те же элементами (вдоль оси 1(столбцы)), и еще,  дополнительно, сделайте этот массив двумерным.

In [4]:
import numpy as np

original_array = np.array([1, 2, 3])

tiled_array =  np.tile(original_array, (2, 4, 2))# повторение массива + сделайте этот массив двумерным

print("Исходный массив:")
print(original_array)

print("Массив с повторенными элементами:")
print(tiled_array)

Исходный массив:
[1 2 3]
Массив с повторенными элементами:
[[[1 2 3 1 2 3]
  [1 2 3 1 2 3]
  [1 2 3 1 2 3]
  [1 2 3 1 2 3]]

 [[1 2 3 1 2 3]
  [1 2 3 1 2 3]
  [1 2 3 1 2 3]
  [1 2 3 1 2 3]]]


4. Предположим, у вас есть два датасета с данными о температуре и влажности. Каждый датасет представлен в виде двумерного массива, где строки представляют дни, а столбцы представляют конкретные моменты времени в течение дня. Тип данных - int. Но вам нужно изменить их на float.

Создайте функцию, которая принимает на вход два аргумента: dataset и new_dtype.
Используйте функцию для изменения типа данных каждого датасета на тип float.

In [5]:
import numpy as np

temp_data = np.array([[22, 25, 24, 23, 21],
                      [20, 18, 19, 22, 24]])

humid_data = np.array([[45, 50, 48, 52, 47],
                       [45, 48, 50, 51, 53]])

def change_data_type(dataset, new_dtype): 
    return dataset.astype(new_dtype)

temp_data = change_data_type(temp_data, float)
humid_data = change_data_type(humid_data, float) 

print(f'Новый тип данных temp_data: {temp_data.dtype}')
print(f'Новый тип данных humid_data: {humid_data.dtype}')

Новый тип данных temp_data: float64
Новый тип данных humid_data: float64


5. Выберите все элементы второй строки для каждой матрицы.

In [6]:
import numpy as np
tensor = np.array([[[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]],

                   [[10, 11, 12],
                    [13, 14, 15],
                    [16, 17, 18]],

                   [[19, 20, 21],
                    [22, 23, 24],
                    [25, 26, 27]]])

result = tensor[:, 1, :] 

print(f'Все элементы вдоль второго измерения для каждой матрицы:\n{result}')

Все элементы вдоль второго измерения для каждой матрицы:
[[ 4  5  6]
 [13 14 15]
 [22 23 24]]


6. Выберите элементы в каждой матрице в нижнем правом углу, начиная с третьей строки и третьего столбца и до конца каждой матрицы. Обратите внимание - результат должен быть трехмерным массивом, где каждая подматрица содержит элементы в нижнем правом углу соответствующей матрицы.

In [7]:
import numpy as np
tensor = np.array([[[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]],

                   [[10, 11, 12],
                    [13, 14, 15],
                    [16, 17, 18]],

                   [[19, 20, 21],
                    [22, 23, 24],
                    [25, 26, 27]]])

result =  tensor[:, 2:3, 2:3]

print(f'Элементы в каждой матрице в нижнем правом угле:\n{result}')

Элементы в каждой матрице в нижнем правом угле:
[[[ 9]]

 [[18]]

 [[27]]]


7. Выберите из 2D массива matrix все строки, в которых есть хотя бы одно число больше 7.

In [ ]:
import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

result =  matrix[np.any(matrix > 7, 1)]

print(result)

8. Замените в массиве arr все четные числа на 0.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

arr[arr % 2 == 0] = 0 

print(arr)

9. Предположим, у вас есть набор данных о продажах товаров, представленный в виде двумерного массива sales_data_array. Каждая строка представляет собой информацию о продажах для конкретного товара, а столбцы содержат следующую информацию: номер товара, количество проданных единиц, и доход от продаж.

Ваша задача - проверить следующие условия:

Есть ли хотя бы одна запись с нулевыми продажами (количество проданных единиц равно 0)?
Все ли товары имеют положительный доход от продаж?

In [ ]:
import numpy as np

sales_data_array = np.array([[1, 10, 100],
                             [2, 5, 50],
                             [3, 0, 0],
                             [4, 8, 80]])

def analyze_sales_data(sales_data):
    has_zero_sales = np.any(sales_data[:, 1] == 0) # проверка, есть ли хотя бы одна запись с нулевыми продажами
    all_positive_income = np.all(sales_data[:, 2] > 0) # проверка, все ли товары имеют положительный доход от продаж

    return [has_zero_sales, all_positive_income]  

result =  analyze_sales_data(sales_data_array)

print(f"Есть ли товары с нулевыми продажами: {result[0]}")  
print(f"Все ли товары имеют положительный доход: {result[1]}")  

10. Дан массив data, содержащий информацию о студентах: имя, возраст, пол, курс и средний балл. Найдите имена, средние баллы и другую информацию студентов, которые старше 20 лет, женского пола и учатся на третьем курсе. 

In [10]:
import numpy as np

data = np.array([
    ['Анна', 19, 'F', 1, 4.5],
    ['Борис', 21, 'M', 2, 3.7],
    ['Вера', 21, 'F', 3, 4.8],
    ['Глеб', 22, 'M', 4, 3.9],
    ['Дарья', 18, 'F', 1, 4.2],
    ['Егор', 23, 'M', 3, 4.1],
    ['Жанна', 21, 'F', 2, 4.6],
    ['Захар', 19, 'M', 1, 4.0]
])


mask =  (data[:, 1].astype(int) > 20) & (data[:, 2] == 'F') & (data[:, 3].astype(int) == 3)
result =  data[mask]

print(result)

[['Вера' '21' 'F' '3' '4.8']]


11. Транспонировать только те строки, у которых первый элемент больше 3

In [ ]:
import numpy as np

# Заданная матрица A
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16],
              [17, 18, 19, 20]])

condition = A[:, 0] > 3 

A[condition] = A[condition].T  

print("Матрица A после транспонирования строк с первым элементом больше 3:")
print(A)

12. Транспонируйте верхний левый квадрант матрицы A.

In [ ]:
import numpy as np

A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

A =  np.transpose(A[:2, :2], (1, 0))

print("Матрица A после транспонирования верхнего левого квадранта:")
print(A)

13. Создайте массив размером 2x8, заполненный значениями от 0 до 15.

In [1]:
import numpy as np

arr = np.arange(0,16)
arr_r = np.reshape(arr, (2, 8))


print("Массив:")
print(arr_r)

14. У нас есть массив цен prices и ставка НДС vat_rate, и вам нужно рассчитать стоимость товаров с учетом НДС.

In [ ]:
import numpy as np

prices = np.array([25.50, 12.75, 18.90, 30.25, 15.60])
vat_rate = 0.20

prices_with_vat =  np.add(np.multiply(prices, vat_rate), prices)

print("Стоимость товаров с НДС:", prices_with_vat)

15. У вас есть массив, представляющий собой скорости движения транспортного средства в км/ч: speeds = np.array([60, 75, 90, 100, 80, 65]). Напишите программу для определения времени в пути для каждой скорости при преодолении расстояния 150 км с учетом замедления движения на 20%. Когда будете считать время, округлите  результат вниз, возвращая только целую часть.

In [ ]:
import numpy as np

speeds = np.array([60, 75, 90, 100, 80, 65])
distance = 150
slowdown_rate = 0.20

adjusted_speeds =  np.subtract(speeds, np.multiply(speeds, slowdown_rate)) 
travel_times =  np.floor(np.divide(distance, adjusted_speeds)) 

print("Время в пути для каждой скорости:", travel_times)

16.Используйте методы NumPy, чтобы получить новый массив, где каждый элемент равен 1, если классификации (classification1 и classification2) совпадают, и 0 в противном случае.

In [ ]:
import numpy as np

classification1 = np.array([[1, 0, 1], 
                            [0, 1, 0]])
classification2 = np.array([[1, 0, 0], 
                            [0, 1, 1]])

result = np.equal(classification1, classification2).astype(int) 

print(result)

17. Есть два массива, celsius_temps представляющий температуру в градусах Цельсия и days представляющий дни в которые эта температура была зарегистрирована. Определите, в какие дни температура в Фаренгейтах была выше 90, а в Цельсиях не ниже 30.

In [ ]:
import numpy as np

celsius_temps = np.array([25, 32, 28, 35, 30]) 
days = np.array(['понедельник', 'вторник', 'среда', 'четверг', 'пятница']) 

fahrenheit_temps = np.add(np.divide(np.multiply(celsius_temps, 9), 5), 32) # температура в Фаренгейтах

hot_days_fahrenheit_temps = days[fahrenheit_temps > 90] # дни когда температура в Фаренгейтах была выше 90
hot_days_celsius_temps = days[celsius_temps >= 30] # дни когда температура в Цельсиях не ниже 30

print(f'Температура выше 90 по Фаренгейту: {hot_days_fahrenheit_temps}')
print(f'Температура не ниже 30 Цельсия: {hot_days_celsius_temps}')

18. Есть массив, представляющий возрастающую последовательность чисел. Определите, какие числа удовлетворяют критериям: больше 10 и не больше 30, и не равны 15.

In [ ]:
import numpy as np

numbers = np.array([5, 12, 15, 20, 25, 30, 35])

condition1 = (numbers > 10) & (numbers <= 30) 
condition2 = numbers != 15 


    
filtered_numbers = numbers[condition1 & condition2]

print(f'Числа, удовлетворяющие условиям: {filtered_numbers}')

19. Создайте новый массив,  который содержит 'A' для элементов больше 5, 'B' для элементов от 1 до 5 включительно и 'C' в противном случае.

In [ ]:
import numpy as np

arr = np.array([3, 8, 1, 6, 0, 7])

result_arr = np.where(arr > 5, 'A', np.where(arr == 0, 'C', 'B')) 
print("Массив arr:")
print(arr)
print("Итоговый массив:")
print(result_arr)

20. Представим, что у вас есть данные о ежедневных изменениях стоимости акций компании. Используйте методы для анализа финансовых показателей. Найдите изменение цен за каждый день, а также дни с минимальным и максимальным изменением.

In [ ]:
import numpy as np

stock_prices = np.array([50, 55, 60, 52, 48, 65, 70])
days = np.array(['понедельник', 'вторник', 'среда', 'четверг', 'пятница', 'суббота', 'воскресенье'])

daily_returns = np.diff(stock_prices)
best_day = days[np.argmax(daily_returns) + 1] 
worst_day = days[np.argmin(daily_returns) + 1]


print(f"Изменения цен за день: {daily_returns}")
print(f"Лучший день: {best_day}")
print(f"Худший день: {worst_day}")

21. Найдите среднюю стоимость акций каждой компании за все дни. Затем определите компанию с максимальной волатильностью (наибольшим размахом цен). И под конец, найдите день с наибольшим общим изменением в стоимости акций всех компаний.

In [1]:
import numpy as np

# Цены акций для 3 компаний(каждый столбец - отдельная компания)
stock_prices = np.array([
    [110, 112, 108],
    [115, 118, 120],
    [108, 110, 105],
    [122, 121, 124],
    [128, 130, 125],
    [133, 132, 134],
    [129, 127, 130]
])

average_prices = np.mean(stock_prices, axis=0).round(2)

volatility = np.ptp(stock_prices, axis=0) 
most_volatile_company = np.argmax(volatility) 

total_daily_change = np.diff(np.sum(stock_prices, axis=1))     
day_with_max_change = np.argmax(total_daily_change) + 1

print("Средняя стоимость акций каждой компании:", average_prices) 
print("Индекс самой волатильной компании:", most_volatile_company) 
print("Индекс дня с наибольшим изменением в стоимости акций:", day_with_max_change)

Средняя стоимость акций каждой компании: [120.71 121.43 120.86]
Индекс самой волатильной компании: 2
Индекс дня с наибольшим изменением в стоимости акций: 3


22. У вас есть два массива целых чисел, arr1 и arr2. Ваша задача - найти и вывести объединение уникальных элементов обоих массивов, а также определить те числа, которые встречаются и в arr1, и в arr2. 

In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([3, 4, 5, 6, 7])

unique_arr1 = np.unique(arr1) 
unique_arr2 = np.unique(arr2) 

union = np.union1d(unique_arr1, unique_arr2) 

in_arr1_mask = np.in1d(union, arr1) 
in_arr2_mask = np.in1d(union, arr2) 

common_elements_mask = np.in1d(union, np.intersect1d(arr1, arr2)) 
common_elements = union[common_elements_mask] 

print("Объединение уникальных элементов:", union)
print("Маска для вхождения в arr1:", in_arr1_mask)
print("Маска для вхождения в arr2:", in_arr2_mask)
print("Маска для общих элементов:", common_elements_mask)
print("Элементы, встречающиеся и в arr1, и в arr2:", common_elements)

23. Удалите из массива arr все элементы, которые встречаются более одного раза.

In [ ]:
import numpy as np

arr = np.array([3, 2, 4, 1, 5, 2, 6, 4, 7])

unique_elements, counts = np.unique(arr, return_counts=True) 
elements_to_remove = unique_elements[counts > 1]  

filtered_arr = arr[np.in1d(arr, elements_to_remove) == False] 

print("Исходный массив:", arr)
print("Массив после удаления элементов, встречающихся более одного раза:", filtered_arr)